name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install ttkbootstrap

    - name: Build Exe
      run: |
        python -m nuitka --standalone --windows-disable-console --windows-icon-from-ico="icon.ico" app.py   # 请根据需要修改参数

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-artifact
        path: './app.dist'
